name: 构建TDLib C库

on:
  push:
    branches:
      - '*'

jobs:
  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        platform:
          - arch: x86
            target: Win32

    steps:
      - name: Get current date
        id: date
        run: |
          echo "::set-output name=today::$(date +'%Y-%m-%d')"

      - name: Install packages
        run: |
          vcpkg install gperf:${{ matrix.platform.arch }}-windows openssl:${{ matrix.platform.arch }}-windows zlib:${{ matrix.platform.arch }}-windows

      - name: Clone TDLib
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0  # Fetch all history so we can checkout any branch

      - name: Build For Windows C (through JSON interface)
        shell: pwsh
        run: |
          Remove-Item build -Force -Recurse -ErrorAction SilentlyContinue
          Remove-Item tdlib -Force -Recurse -ErrorAction SilentlyContinue
          mkdir build
          cd build
          cmake -A ${{ matrix.platform.target }} -DCMAKE_INSTALL_PREFIX:PATH=../tdlib -DCMAKE_TOOLCHAIN_FILE:FILEPATH=C:/vcpkg/scripts/buildsystems/vcpkg.cmake ..
          cmake --build . --target install --config Release
          copy Release\tg_cli.exe ..\tdlib\bin
          cd ..
          Compress-Archive $(Resolve-Path tdlib/*) ${{ github.ref_slug }}-for-C.zip

      - name: Upload
        uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ github.ref_slug }}*.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          name: TDLib-${{ github.ref_slug }}
          draft: false
          allowUpdates: true
          replacesArtifacts: true
          body: "TDLib自动化构建发布包"
